language: ruby
env:
  - RAILS_ENV=test
cache:
  - bundler: true
services:
  - mysql 
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e "CREATE DATABASE deploycapistrano_test;"
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
